### ISSUE TITLE
Meteor settings public is undefined

### ISSUE THREAD

**Issue by Flowtter** [l3mpire/lemverse#131] opened 2022-09-20 09:06 UTC
We noticed that under a lot of stress on the CPU, users could not connect anymore.
In the function `restrictedRegistration` of the file `form-account.js`, the variable `const { permissions } = Meteor.settings.public;` is undefined.
The function then tries to access the field `allowAccountCreation`, crashes and the user can't connect since it `cannot read property 'allowAccountCreation' of undefined`.

**Comment by ramnes** [comment] 2022-09-20 14:25
For now we're digging for the root cause but we'll provide step-by-step instructions if we can't fix it by ourselves. :)

**Comment by ramnes** [comment] 2022-10-04 08:55
Closing as we're most likely not going to fix this independently. It's a side effect of a more general problem (namely #80).

**Closed by ramnes** 2022-10-04 08:55 UTC
Labels: bug, up-for-grabs
